# Generated by Django 5.0.4 on 2024-04-30 18:42

import django.db.models.deletion
import utilities.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_field_name', models.CharField(max_length=50, verbose_name="Olympiad Field's Name")),
                ('olympiad_field_schedule', models.TextField(max_length=200, verbose_name="Olympiad Field's Schedule")),
                ('slug', models.SlugField(verbose_name="Olympiad Field's Schedule")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad_field_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher', verbose_name="Olympiad Field's Teacher")),
            ],
            options={
                'verbose_name': 'Olympiad Field',
                'verbose_name_plural': 'Olympiad Fields',
                'db_table': 'olympiad_fields',
                'ordering': ['olympiad_field_name'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiadfield', verbose_name='Olympiad Field')),
                ('olympiad_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Olympiad Student',
                'verbose_name_plural': 'Olympiad Students',
                'db_table': 'olympiad_students',
                'ordering': ['olympiad_field'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_practice_date', models.DateField(verbose_name='Olympiad Practice Date')),
                ('photo', utilities.utils.CompressedImageField(default='no-image.png', help_text='photo format png/jpg', quality=50, upload_to='ekskul/osn', verbose_name='Upload Photo')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olympiad_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiadfield', verbose_name='Olympiad Field')),
                ('olympiad_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Olympiad Teacher')),
                ('students', models.ManyToManyField(to='olympiads.olympiadstudent', verbose_name="Student's Presence")),
            ],
            options={
                'verbose_name': 'Olympiad Report',
                'verbose_name_plural': 'Olympiad Reports',
                'db_table': 'olympiad_reports',
                'ordering': ['-olympiad_practice_date'],
            },
        ),
        migrations.AddIndex(
            model_name='olympiadfield',
            index=models.Index(fields=['id'], name='olympiad_fi_id_88e394_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadstudent',
            index=models.Index(fields=['id'], name='olympiad_st_id_997c62_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiadreport',
            index=models.Index(fields=['id'], name='olympiad_re_id_657982_idx'),
        ),
    ]
