# Generated by Django 5.0.4 on 2024-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiadreport',
            name='olympiad_teacher',
        ),
        migrations.AddField(
            model_name='olympiadreport',
            name='olympiad_level',
            field=models.CharField(blank=True, choices=[(None, 'Choose Olympiad Level'), ('Sekolah', 'School'), ('Kota/Kab', 'City/Regency'), ('Provinsi', 'Province'), ('Nasional', 'Nasional')], max_length=50, null=True, verbose_name='Olympiad Level'),
        ),
    ]
