# Generated by Django 5.0.4 on 2024-05-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(blank=True, choices=[(None, 'Choose Semester'), ('Ganjil', 'Odd'), ('Genap', 'Even')], max_length=10, null=True, verbose_name='Semester'),
        ),
    ]
