# Generated by Django 5.0.4 on 2024-04-30 18:42

import django.db.models.deletion
import utilities.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracurricular', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('report_note', models.TextField(blank=True, max_length=200, verbose_name='Report Note')),
                ('report_photo', utilities.utils.CompressedImageField(default='no-image.png', help_text='photo format png/jpg', quality=50, upload_to='ekskul/laporan', verbose_name='Report Photo')),
                ('academic_year', models.CharField(default='2024/2025', max_length=50, verbose_name='Academic Year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracurricular.extracurricular', verbose_name='Extracurricular Name')),
                ('students', models.ManyToManyField(to='extracurricular.studentextracurricular', verbose_name='Students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['id'], name='reports_id_0103e5_idx')],
            },
        ),
    ]
