# Generated by Django 5.0.4 on 2024-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='Url Name')),
                ('menu_title', models.CharField(max_length=100, verbose_name='Menu Title')),
                ('menu_arabic_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arabic Title')),
                ('icon_data', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Icon data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
                'ordering': ['menu_title'],
                'indexes': [models.Index(fields=['id'], name='menus_id_c2772b_idx')],
            },
        ),
    ]
